project: 
  type: website

website: 
  title: "Sean Vieau Portfolio"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - text: Advanced Data Analyses
        menu:
          - text: Regression (R)
            href: Project_1_Regression/Project_1_Regression_R/Project_1_Regression.qmd
          - text: Regression (SAS)
            href: _site/Project_1_Regression/Project_1_Regression_SAS/Project_1_Regression_SAS.html
          - text: Regression with Moderator (R)
          - text: Regression with Moderator (SAS)
      - text: Data Wrangling
      - text: Clinical Research Informatics
      - text: CV
